### ISSUE TITLE
No publication date found

### ISSUE THREAD

**Issue by daviddavo** [cthoyt/zenodo-client#39]
I'm trying to update some dataset nightly, but it fails every night and, when I go to Zenodo, it turns out that the publication date field is empty

![image](https://github.com/cthoyt/zenodo-client/assets/10263941/0419cda9-73bb-4033-998c-19181cd6a708)

I tried to replicate the error in Zenodo Sandbox, but I couldn't...

In case it helps, this is the tracelog from when it fails uploading:
```
Traceback (most recent call last):
Uploading to zenodo
  File "/opt/hostedtoolcache/Python/3.12.3/x64/bin/dao-utils-upload-dw", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/dao_analyzer/cache_scripts/utils/uploadDataWarehouse.py", line 137, in main
    archiveToZenodo(tmpdir, args.zenodo_max_retries)
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/dao_analyzer/cache_scripts/utils/uploadDataWarehouse.py", line 82, in archiveToZenodo
    raise e
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/dao_analyzer/cache_scripts/utils/uploadDataWarehouse.py", line 75, in archiveToZenodo
    uploadToZenodo([zpath / 'archive.zip'])
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/dao_analyzer/cache_scripts/utils/uploadDataWarehouse.py", line 64, in uploadToZenodo
    raise e
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/dao_analyzer/cache_scripts/utils/uploadDataWarehouse.py", line 55, in uploadToZenodo
    z.update(ZENODO_DEPOSITION_ID, paths)
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/zenodo_client/api.py", line 2[31](https://github.com/Grasia/dao-scripts/actions/runs/9217342059/job/25359211826#step:6:32), in update
    new_deposition_id, new_deposition_data = self._update_submitted_deposition_metadata(deposition_id, res)
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/zenodo_client/api.py", line 279, in _update_submitted_deposition_metadata
    res.raise_for_status()
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: BAD REQUEST for url: https://zenodo.org/api/deposit/depositions/11271085?access_token=***
```

And this is the code I used:

https://github.com/Grasia/dao-scripts/blob/2e2013b5a502de9d7a0a9e1ee169459869b4af68/src/utils/uploadDataWarehouse.py#L47-L64

**Comment by daviddavo** [comment]
I realized that there's no version either...

**Comment by daviddavo** [comment]
The problem seems to be with the grant `05r0vyz12::RTI2018\\u2010096820\\u2010A\\u2010I00`, which uses invalid characters

**Comment by daviddavo** [comment]
The problem was not with the invalid characters, it was with the accepted funders DOI prefixes. See https://developers.zenodo.org/#representation and go to `grants`

They will eventually change to a [new API](https://inveniordm.docs.cern.ch/reference/rest_api_drafts_records/) that supports this
